<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Alga.wwwcore</PackageId>
    <Version>5.0.0</Version>
    <Author>rtink.git@gmail.com</Author>
    <Product>wwwcore</Product>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/rtink-git/Alga.wwwcore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="">
        <Link>README.md</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUglify" Version="1.21.17" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core/HtmlGenerator/BaseMetaGenerator/" />
    <Folder Include="Core/HtmlGenerator/PageCssFile/" />
    <Folder Include="Core/HtmlGenerator/PageJsFile/" />
    <Folder Include="Core/UseCases/" />
  </ItemGroup>

</Project>
